/// Module 1 — one row per segment: counts, RFM means, share of customers and revenue.
table 'Segment Profiles'
	lineageTag: ef003998-98bd-4612-81db-bd3b4ebb9452

	column IsActive
		dataType: boolean
		lineageTag: 201e7d22-af54-4650-a1db-ad7549976dc9
		summarizeBy: none
		sourceColumn: IsActive

	column Status
		dataType: string
		lineageTag: 30f8b949-9f5d-49d0-8dd2-98f6e3ec5a96
		summarizeBy: none
		sourceColumn: Status

	column Segment
		dataType: string
		lineageTag: 6ceae391-fabd-4083-8c20-145a96891640
		summarizeBy: none
		sourceColumn: Segment
		sortByColumn: 'Segment Order'

	column n
		dataType: int64
		lineageTag: 296d458a-b35e-43d6-a3bf-386062a438ce
		summarizeBy: sum
		sourceColumn: n

	column Recency
		dataType: double
		formatString: 0.0
		lineageTag: a3913a94-c80d-4979-8021-95b658a0938f
		summarizeBy: none
		sourceColumn: Recency

	column Frequency
		dataType: double
		formatString: 0.0
		lineageTag: 5d7cdcc2-42e4-4078-b6ef-cd6a5727e041
		summarizeBy: none
		sourceColumn: Frequency

	column Monetary
		dataType: double
		formatString: #,0
		lineageTag: 17e2cf65-d03f-49e7-84e1-c87548f6b7da
		summarizeBy: none
		sourceColumn: Monetary

	column MonthlyRevenueRate
		dataType: double
		formatString: #,0
		lineageTag: c4ad9996-f74e-4807-9db3-c119aa2446c3
		summarizeBy: none
		sourceColumn: MonthlyRevenueRate

	column ActiveMonths
		dataType: double
		formatString: 0.0
		lineageTag: 2facb800-4179-496f-8f8b-66a9b49c8e5d
		summarizeBy: none
		sourceColumn: ActiveMonths

	column SharePctCustomers
		dataType: double
		formatString: 0.0
		lineageTag: 8c33b005-b2e7-47b0-921a-9fee30e601ac
		summarizeBy: none
		sourceColumn: SharePctCustomers

	column SharePctRevenue
		dataType: double
		formatString: 0.0
		lineageTag: 3ef60588-4830-453c-8fc1-a119df38cd2c
		summarizeBy: none
		sourceColumn: SharePctRevenue

	column 'Segment Order'
		dataType: int64
		isHidden
		lineageTag: 4a431a65-f0da-4105-9c06-b7a2cea19b5c
		summarizeBy: none
		sourceColumn: Segment Order

	partition 'Segment Profiles' = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\User\Documents\Coding Projects\Cortonis-Pharma-Sales-Advanced-Analytics\results\generated\customer_segment_profiles.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"IsActive", type logical}, {"Status", type text}, {"Segment", type text}, {"n", Int64.Type}, {"Recency", type number}, {"Frequency", type number}, {"Monetary", type number}, {"MonthlyRevenueRate", type number}, {"ActiveMonths", type number}, {"SharePctCustomers", type number}, {"SharePctRevenue", type number}}),
				  WithOrder = Table.AddColumn(Typed, "Segment Order", each if [Segment] = "Key Accounts" then 1 else if [Segment] = "Core Active" then 2 else if [Segment] = "Dormant - High Potential (Win-back)" then 3 else if [Segment] = "Dormant - Low Value" then 4 else 99, Int64.Type)
				in
				  WithOrder

